export enum Food {
  CHICKEN_BREAST = 'chicken_breast',
  BOILED_EGG = 'boiled_egg',
  BROWN_RICE_COOKED = 'brown_rice_cooked',
  BLACK_BEANS_COOKED = 'black_beans_cooked',
  OATS = 'oats',
  BANANA = 'banana',
  APPLE = 'apple',
  SWEET_POTATO_COOKED = 'sweet_potato_cooked',
  SALMON_GRILLED = 'salmon_grilled',
  TUNA_CANNED_WATER = 'tuna_canned_water',
  COTTAGE_CHEESE = 'cottage_cheese',
  GREEK_YOGURT_PLAIN = 'greek_yogurt_plain',
  QUINOA_COOKED = 'quinoa_cooked',
  BROCCOLI_COOKED = 'broccoli_cooked',
  ALMONDS = 'almonds',
  AVOCADO = 'avocado',
  WHOLE_WHEAT_BREAD = 'whole_wheat_bread',
  SKIM_MILK = 'skim_milk',
  LENTILS_COOKED = 'lentils_cooked',
  OLIVE_OIL = 'olive_oil',
}
