// InjuryFactor values - using const object instead of enum to allow duplicate values
export const InjuryFactor = {
  // Não utilizar
  NAO_UTILIZAR: 1.0,

  // Harris-benedict (1919)
  PACIENTE_NAO_COMPLICADO: 1.0,
  POS_OPERATORIO_CANCER: 1.1,
  FRATURA: 1.2,
  SEPSE: 1.3,
  PERITONITE: 1.4,
  MULTITRAUMA_REABILITACAO: 1.5,
  MULTITRAUMA_SEPSE: 1.6,
  QUEIMADURA_ATE_20: 1.25,
  QUEIMADURA_30_50: 1.7,
  QUEIMADURA_50_70: 1.8,
  QUEIMADURA_70_90: 2.0,
  QUEIMADURA_100: 2.1,

  // Long (1979)
  CANCER: 1.27,
  CIRURGIA_ELETIVA: 1.1,
  DESNUTRICAO_GRAVE: 1.5,
  DOENCA_CARDIOPULMONAR: 0.9,
  DOENCA_CARDIOPULMONAR_CIRURGIA: 1.42,
  FRATURAS_MULTIPLAS: 1.27,
  INFECCAO_GRAVE: 1.32,
  INSUFICIENCIA_CARDIACA: 1.4,
  INSUFICIENCIA_HEPATICA: 1.42,
  INSUFICIENCIA_RENAL_AGUDA: 1.3,
  JEJUM: 0.9,
  POS_OPERATORIO_CIRURGIA_CARDIACA: 1.35,
  PANCREATITE: 1.55,
  PEQUENA_CIRURGIA: 1.2,
  PEQUENO_TRAUMA_TECIDO: 1.25,
  POS_OPERATORIO_GERAL: 1.25,
  POS_OPERATORIO_TORACICO: 1.35,
  SEPSE_LONG: 1.6,
  TRANSPLANTE_FIGADO: 1.35,
  TRANSPLANTE_MEDULA_OSSEA: 1.25,
} as const;

// Type for InjuryFactor values
export type InjuryFactor = (typeof InjuryFactor)[keyof typeof InjuryFactor];
